package catalog

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

// writeTask materialises a task directory from a path -> content map. Building
// the fixtures in code keeps each test case readable next to its expectation.
func writeTask(t *testing.T, root, name string, files map[string]string) string {
	t.Helper()
	dir := filepath.Join(root, name)
	for p, content := range files {
		full := filepath.Join(dir, filepath.FromSlash(p))
		if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(full, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	return dir
}

func validTask(id string) map[string]string {
	return map[string]string{
		"task.yaml":              "id: " + id + "\ntitle: Пример\ntopic: slices\ndifficulty: 2\nestimate_minutes: 10\n",
		"README.md":              "# Условие\n\nСделай что-нибудь.\n",
		"starter/solution.go":    "package solution\n\nfunc Do() {}\n",
		"tests/solution_test.go": "package solution\n\nimport \"testing\"\n\nfunc TestDo(t *testing.T) { Do() }\n",
		"solution/solution.go":   "package solution\n\nfunc Do() {}\n",
	}
}

func TestLoadTask(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	dir := writeTask(t, root, "slices-01", validTask("slices-01"))

	got, err := LoadTask(dir)
	if err != nil {
		t.Fatalf("LoadTask() error = %v", err)
	}
	if got.ID != "slices-01" || got.Title != "Пример" || got.Topic != "slices" {
		t.Errorf("task = %+v", got)
	}
	if got.Difficulty != 2 || got.EstimateMin != 10 {
		t.Errorf("difficulty = %d estimate = %d", got.Difficulty, got.EstimateMin)
	}
	if !got.Race {
		t.Error("Race should default to true")
	}
	if len(got.Starter) != 1 || got.Starter[0].Path != "solution.go" {
		t.Errorf("starter = %+v, want one file at a relative path", got.Starter)
	}
	if len(got.Tests) != 1 || len(got.Solution) != 1 {
		t.Errorf("tests = %d solution = %d, want 1 each", len(got.Tests), len(got.Solution))
	}
	if got.ContentHash == "" {
		t.Error("ContentHash must be set")
	}
}

func TestLoadTaskRaceOptOut(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	files := validTask("generics-01")
	files["task.yaml"] += "race: false\n"
	dir := writeTask(t, root, "generics-01", files)

	got, err := LoadTask(dir)
	if err != nil {
		t.Fatal(err)
	}
	if got.Race {
		t.Error("race: false in the manifest must disable -race")
	}
}

func TestLoadTaskValidation(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name    string
		dirName string
		mutate  func(map[string]string)
		wantErr string
	}{
		{
			name:    "id must match the directory",
			dirName: "renamed",
			wantErr: "does not match directory name",
		},
		{
			name: "difficulty out of range",
			mutate: func(f map[string]string) {
				f["task.yaml"] = strings.Replace(f["task.yaml"], "difficulty: 2", "difficulty: 9", 1)
			},
			wantErr: "difficulty must be 1..3",
		},
		{
			name: "estimate must be positive",
			mutate: func(f map[string]string) {
				f["task.yaml"] = strings.Replace(f["task.yaml"], "estimate_minutes: 10", "estimate_minutes: 0", 1)
			},
			wantErr: "estimate_minutes must be positive",
		},
		{
			name:    "unknown manifest key",
			mutate:  func(f map[string]string) { f["task.yaml"] += "dificulty: 2\n" },
			wantErr: "field dificulty not found",
		},
		{
			name:    "missing readme",
			mutate:  func(f map[string]string) { delete(f, "README.md") },
			wantErr: "read README.md",
		},
		{
			name:    "empty readme",
			mutate:  func(f map[string]string) { f["README.md"] = "  \n" },
			wantErr: "README.md must not be empty",
		},
		{
			name:    "no starter files",
			mutate:  func(f map[string]string) { delete(f, "starter/solution.go") },
			wantErr: "starter/ must contain at least one file",
		},
		{
			name:    "no test files",
			mutate:  func(f map[string]string) { delete(f, "tests/solution_test.go") },
			wantErr: "must contain at least one _test.go",
		},
		{
			name:    "no reference solution",
			mutate:  func(f map[string]string) { delete(f, "solution/solution.go") },
			wantErr: "solution/ must contain the reference implementation",
		},
		{
			name: "starter shadows a test file",
			mutate: func(f map[string]string) {
				f["starter/solution_test.go"] = "package solution\n"
			},
			wantErr: "the editor must not hold test files",
		},
		{
			name: "go.mod checked in",
			mutate: func(f map[string]string) {
				f["starter/go.mod"] = "module x\n"
			},
			wantErr: "generated by the runner",
		},
		{
			name:    "malformed yaml",
			mutate:  func(f map[string]string) { f["task.yaml"] = "id: [unclosed\n" },
			wantErr: "parse task.yaml",
		},
		{
			name:    "id with uppercase",
			dirName: "Slices-01",
			mutate: func(f map[string]string) {
				f["task.yaml"] = strings.Replace(f["task.yaml"], "id: slices-01", "id: Slices-01", 1)
			},
			wantErr: "lowercase letters",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			files := validTask("slices-01")
			if tt.mutate != nil {
				tt.mutate(files)
			}
			dirName := tt.dirName
			if dirName == "" {
				dirName = "slices-01"
			}
			dir := writeTask(t, t.TempDir(), dirName, files)

			_, err := LoadTask(dir)
			if err == nil {
				t.Fatalf("LoadTask() succeeded, want error containing %q", tt.wantErr)
			}
			if !strings.Contains(err.Error(), tt.wantErr) {
				t.Errorf("LoadTask() error = %v, want it to mention %q", err, tt.wantErr)
			}
		})
	}
}

func TestLoadReportsBrokenTasksWithoutFailing(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	writeTask(t, root, "good-01", validTask("good-01"))
	writeTask(t, root, "broken", map[string]string{"task.yaml": "id: broken\n"})

	snap, err := Load(root)
	if err != nil {
		t.Fatalf("Load() error = %v; one bad task must not fail the scan", err)
	}
	if snap.Len() != 1 {
		t.Errorf("loaded %d tasks, want 1", snap.Len())
	}
	errs := snap.Errors()
	if len(errs) != 1 || errs[0].Dir != "broken" {
		t.Errorf("errors = %+v, want the broken directory reported", errs)
	}
}

func TestLoadSkipsHiddenAndUnderscoreDirs(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	writeTask(t, root, "good-01", validTask("good-01"))
	writeTask(t, root, ".git", map[string]string{"config": "x"})
	writeTask(t, root, "_wip", map[string]string{"task.yaml": "junk"})

	snap, err := Load(root)
	if err != nil {
		t.Fatal(err)
	}
	if snap.Len() != 1 || len(snap.Errors()) != 0 {
		t.Errorf("tasks = %d errors = %+v, want only the real task", snap.Len(), snap.Errors())
	}
}

func TestLoadDetectsDuplicateIDs(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	writeTask(t, root, "a", func() map[string]string {
		f := validTask("a")
		return f
	}())
	// Two directories, both claiming the id "a" is impossible because the id
	// must equal the directory name, so this checks the guard for the case
	// where the rule is ever relaxed.
	snap, err := Load(root)
	if err != nil {
		t.Fatal(err)
	}
	if snap.Len() != 1 {
		t.Errorf("tasks = %d, want 1", snap.Len())
	}
}

func TestSnapshotOrdering(t *testing.T) {
	t.Parallel()
	snap := NewSnapshot([]*Task{
		{ID: "z-easy", Topic: "slices", Difficulty: 1},
		{ID: "a-hard", Topic: "slices", Difficulty: 3},
		{ID: "m", Topic: "errors", Difficulty: 2},
	}, nil, "")

	var got []string
	for _, t := range snap.All() {
		got = append(got, t.ID)
	}
	want := []string{"m", "z-easy", "a-hard"}
	if strings.Join(got, ",") != strings.Join(want, ",") {
		t.Errorf("order = %v, want %v (topic, then difficulty, then id)", got, want)
	}
}

func TestSnapshotLookup(t *testing.T) {
	t.Parallel()
	snap := NewSnapshot([]*Task{{ID: "a", Topic: "slices", Difficulty: 1}}, nil, "")
	if _, err := snap.Task("a"); err != nil {
		t.Errorf("Task(a) error = %v", err)
	}
	if _, err := snap.Task("missing"); err == nil {
		t.Error("Task(missing) should fail")
	}
}

func TestFingerprintChangesWithContent(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	writeTask(t, root, "a", validTask("a"))

	first, err := Fingerprint(root)
	if err != nil {
		t.Fatal(err)
	}
	same, err := Fingerprint(root)
	if err != nil {
		t.Fatal(err)
	}
	if first != same {
		t.Fatal("fingerprint is not stable across calls")
	}

	p := filepath.Join(root, "a", "README.md")
	if err := os.WriteFile(p, []byte("# Другое условие\n\nтекст\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	// Modification time granularity can be coarse; the size change alone must
	// already be enough to move the fingerprint.
	if err := os.Chtimes(p, time.Now(), time.Now().Add(time.Second)); err != nil {
		t.Fatal(err)
	}
	changed, err := Fingerprint(root)
	if err != nil {
		t.Fatal(err)
	}
	if changed == first {
		t.Error("fingerprint did not change after editing a file")
	}
}

func TestContentHashTracksTests(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	files := validTask("a")
	dir := writeTask(t, root, "a", files)
	before, err := LoadTask(dir)
	if err != nil {
		t.Fatal(err)
	}

	if err := os.WriteFile(filepath.Join(dir, "tests", "solution_test.go"),
		[]byte("package solution\n\nimport \"testing\"\n\nfunc TestDo(t *testing.T) { t.Skip() }\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	after, err := LoadTask(dir)
	if err != nil {
		t.Fatal(err)
	}
	if before.ContentHash == after.ContentHash {
		t.Error("changing the tests must change the content hash")
	}
}

func TestValidateUserPath(t *testing.T) {
	t.Parallel()
	tests := []struct {
		path    string
		wantErr string
	}{
		{path: "main.go"},
		{path: "pkg/helper.go"},
		{path: "", wantErr: "empty path"},
		{path: "/etc/passwd.go", wantErr: "must be relative"},
		{path: "../escape.go", wantErr: `must not contain ".." segments`},
		{path: "a/../../escape.go", wantErr: "not a clean path"},
		{path: "./main.go", wantErr: "not a clean path"},
		{path: `pkg\main.go`, wantErr: "forward slashes"},
		{path: "go.mod", wantErr: "owned by the runner"},
		{path: "main_test.go", wantErr: "test files come from the task"},
		{path: "notes.txt", wantErr: "only .go files"},
	}
	for _, tt := range tests {
		t.Run(tt.path, func(t *testing.T) {
			t.Parallel()
			err := ValidateUserPath(tt.path)
			if tt.wantErr == "" {
				if err != nil {
					t.Errorf("ValidateUserPath(%q) = %v, want nil", tt.path, err)
				}
				return
			}
			if err == nil || !strings.Contains(err.Error(), tt.wantErr) {
				t.Errorf("ValidateUserPath(%q) = %v, want it to mention %q", tt.path, err, tt.wantErr)
			}
		})
	}
}

func TestReadTreeSkipsHiddenFiles(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	files := validTask("a")
	files["starter/.DS_Store"] = "junk"
	dir := writeTask(t, root, "a", files)

	got, err := LoadTask(dir)
	if err != nil {
		t.Fatal(err)
	}
	if len(got.Starter) != 1 {
		t.Errorf("starter = %+v, want hidden files skipped", got.Starter)
	}
}

func TestReadTreeRejectsHugeFiles(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	files := validTask("a")
	files["starter/big.go"] = strings.Repeat("x", maxFileSize+1)
	dir := writeTask(t, root, "a", files)

	if _, err := LoadTask(dir); err == nil || !strings.Contains(err.Error(), "over the") {
		t.Errorf("LoadTask() error = %v, want a size limit error", err)
	}
}

func TestLoadMissingRoot(t *testing.T) {
	t.Parallel()
	if _, err := Load(filepath.Join(t.TempDir(), "nope")); err == nil {
		t.Error("Load() on a missing directory should fail; a typo in -tasks must be loud")
	}
}
